### PR TITLE
Enable video after start only audio call

### PR DESCRIPTION
**Pull request by rscreene**
My attempt at fixing #249 - the re-INVITE is being sent before the video candidates are collected.

I had to do make a couple of changes:
1) Added a media option to the sendReinvite() method so to add video to an audio call you just have to do: `session.sendReinvite({media: { constraints: { video: true } })`
2) Initialised the onIceCompleted promise whenever ICE is started.
3) In MediaHandler.getDescription() set the iceRestart attribute in the RTC constraints if it is necessary.  (I have overloaded the attribute that may be passed to the createOffer() method of PeerConnetion for this).

It works for our requirements but I cannot guarantee that I haven't broken anything.

Please do what you wish to this PR.

### CODE REVIEW

**Comment by rscreene** [comment]
Mmmm, this works fine for Firefox Nightly.  I'm having problems with Chrome.  The stream is set up (I can see it in the statistics), but the onaddstream does not fire.

**Comment by rscreene** [comment]
I have been unable to get this working on Chrome.  So closing this PR.

**Comment by rscreene** [comment]
Got it working on Chrome by handling the stream onaddtrack event.  Re-opening PR.

**Comment by james-onsip** [comment]
- [1st commit](https://github.com/rscreene/SIP.js/commit/1e345a568e0f27a02993dd7578feb1684004d348) looks good

- [2nd commit](https://github.com/rscreene/SIP.js/commit/d71e13e95e1072d1b7c933789f1c74e210789028): I see that iceRestarting was taken off of the RTCConstraints in a later commit, that is definitely preferred to how this commit approached it. Also, it seems that ice will restart if ANY of the conditions are not met, not just the iceRestart (or moreCandidates) variable. Was this intended?

- [3rd commit](https://github.com/rscreene/SIP.js/commit/64b2794d0a14558bc8519802566af718bcac8bd9) looks good, it just corrects an issue I had with the 2nd commit.

- [4th commit] (https://github.com/rscreene/SIP.js/commit/4211228a0f06e44a1b6c14ee6f06a69cd7831b80): While I do think this is a preferable change (as we've dealt with it in our own apps), this may lead to some unexpected behavior. I don't think it would break anything, and if anything is probably expected by users, but holding off on this until 0.8.0 may be necessary.


The PR looks great, thanks for putting the time in to making this work. After clearing up the question I have, as well as thinking about the `onaddtrack` a bit more, I'd say it is ready to be merged. Also, I made some changes to ICE Handling yesterday that may be useful to you, although it would probably just be overkill.

Thanks,
James

**Comment by rscreene** [comment]
@james-onsip Thanks for your comments.  With regards to your question I think the behaviour is fine.  The comment is a bit mis-leading it does not actually invoke ICE restart - ICE restart will be performed automatically  by pc.setLocalDescription().  The else clause simply set the promise when the ICE completes.  There is a corner case where a re-negotiation occurs: the promise will be re-set, but I can't see this having any problems.  Let me know if this doesn't make sense!

**Comment by james-onsip** [comment]
@rscreene,
  Now that I look more at the code, you're right, but there is a difference in functionality, albeit slight. I believe your change is correct for what you are attempting, but either way, I think dropping that whole bit of code is safer.

  The difference in functionality occurs in that now, an ICE collection MUST be occurring in order for `initIceCompleted`'s promise to resolve, whereas before, as long as it completed at any point prior, the code could continue. This is due to the new `deferred` being created for `onIceCompleted`. I guess this used to make sense as you were only worried about onIceCompleted happening once, but with your change it gets a little dicey setting the new `deferred` up AFTER the processing begins. The conditional should guard against this, but I think it can be avoided all together.

What if you were to call `initIceCompleted` before the call to `pc.setLocalDescription` (line 481 or so)? That way, the entire `then` function could just be replaced by `self.onIceCompleted.promise` (I think that should work anyway. That feels safer and cleaner, but I may be missing something. What do you think?

**Comment by rscreene** [comment]
@james-onsip I think you might be right!  If you would like to make the changes I should be able to test them in our environment next week.

**Comment by james-onsip** [comment]
[patchfile.txt](https://github.com/onsip/SIP.js/files/99299/patchfile.txt)

There's the diff/patch that should make the change we discussed. Maybe there's' a better way to do this, but  I couldn't figure it out through github so I figured this works fine. Also, you may want to catch the branch up to master before applying this and retesting, as there is a conflict. A lot of the MediaHandler initialization stuff was moved into a function so it can be reused, and the ICE stuff was also reused, so maybe your code will actually clean up some of that. Let me know if you need a hand with that conflict.

**Comment by rscreene** [comment]
I sitll haven't got my test environment set-up as yet.  I'll try later in the week.

**Comment by rscreene** [comment]
I've tried to get this patch working but failed! (When created an audio-only call I get a PeerConnection failure).  I'll try to debug when I get some free time.

**Comment by james-onsip** [comment]
[patchfile.txt](https://github.com/onsip/SIP.js/files/112388/patchfile.txt)

I think the merge conflicts were resolved incorrectly, and it got rid of one of the functions you made (`initIceCompleted`). I made a new patch, and was able to get an audio call working with it. 

Thanks,
James

**Comment by soulhunter1987** [comment]
Hi. When do you expect to include it into a stable release?

**Comment by james-criscuolo** [comment]
I see we haven't updated this in a while, but that's given it ample time to be tested. Any luck with that, @rscreene?

**Comment by rscreene** [comment]
I'm afraid I got dragged onto something else before I managed to merge. TBH I don't think i'm going to have time to finish it in the immediate future.   Sorry about that.

**Comment by rscreene** [comment]
It looks like I'm able to look at it again.  I'll keep you posted...

**Comment by rscreene** [comment]
Sorry - closed in error!

**Comment by rscreene** [comment]
I've managed to get something working for this now.

The patch supplied by @james-criscuolo works well.  However, I have had to skip a single unit test since the promise always timed-out.

I have used only the PC.onaddstream and Stream.onaddtrack events since these are all that are required for my application (calling FreeSWITCH from Firefox and Chrome).  It will be worth implementing the newer events identified by @soulhunter1987 in #249

**Comment by soulhunter1987** [comment]
What about merging this pull request? If you say it is working... PC.addstream is deprecated and will be removed, but not wery soon till all current WebRTC applications are based on it.

**Comment by james-criscuolo** [comment]
There are two things preventing this from getting merged:

1) Why does that unit test fail? Does that mean that functionality no longer works?

2) The commits can be cleaned up a bit. Currently there are 10, looks like there can be significantly less.

**Comment by wpp** [comment]
Hi all,

FYI: I checked out this branch (rscreene:master) and tested it with a recent Chrome version (51.0.2704.106).

After starting a audio only call **I could not** get the re-invite to work via:

    session.sendReinvite({{media: { constraints: { video: true } });

The initiating side got "stuck" at `this.mediaHandler.getDescription(self.mediaHint)` and never sent the Invite request.

**Comment by soulhunter1987** [comment]
@rscreene ?

**Comment by rscreene** [comment]
My apologies, I haven't had time to get back onto this.  It doesn't look like its going to happen in the short term either.  Sorry for not letting you know sooner.

**Comment by egreenmachine** [comment]
This feature is now covered in [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0). I wrote a [renegotiation guide](https://sipjs.com/guides/renegotiation/) to show users how to do this. 

While we ended up going a different route, we appreciate the effort you put into SIP.js and we hope that you continue to use and contribute to the project. Thanks

**Pull request closed without merging**
