### PR TITLE
Version 0.16.0

### PR DESCRIPTION
**Pull request by john-e-riordan**
This is a work in progress branch for version 0.16.0.

It's being rebased on `dev-master` as work continues there.

Includes...
- remove old api
- remove old tests
- update documentation
- new `README.md` (TODO)

### CODE REVIEW

**Comment by grxnola** [comment]
Why is OpenSIPS no longer supported?

**Comment by egreenmachine** [comment]
@grxnola SIP.js should work with OpenSIPS but we are not officially supporting it in our documentation.

**Comment by hrantbagdasarian** [comment]
Any ETA when this version will be released?

**Comment by egreenmachine** [comment]
0.16 will be no different than the latest 0.15 with the old API removed. If you want to start using it now go for it. We have been using it for several months.

**Pull request merged**
