### PR TITLE
Add diversion header to message

### PR DESCRIPTION
**Pull request by raphaelhovsepyan**

### CODE REVIEW

**Comment by egreenmachine** [comment]
The idea of this is good, but I think that it needs to end up in the grammar

**Comment by egreenmachine** [comment]
The `.pegjs` file is not generated, it is what should be modified.

**Comment by egreenmachine** [comment]
Take a look at the commit history on the file. That should help you.

**Comment by raphaelhovsepyan** [comment]
@egreenmachine @seanbright Thanks for help. Will update in few days. 🙏

**Comment by james-criscuolo** [comment]
Any update here? At this point a bit more work is needed since we've moved to types, but if you still anticipate getting this done then I will leave it open.

**Pull request closed without merging**
