### PR TITLE
Use Chrome headless to run unit tests

### PR DESCRIPTION
**Pull request by jlaine**
PhantomJS has been discontinued, relying on it to run our unit tests
is problematic going forward.

### CODE REVIEW

**Comment by james-criscuolo** [comment]
I believe when I updated the test process a few months back, Travis failing was the exact reason why I didn't switch to Chrome Headless. If you manage to get Travis going (it can be a pain sometimes), we will certainly accept this PR.

**Comment by jlaine** [comment]
Done :)

**Comment by egreenmachine** [comment]
Looks good to me

**Comment by james-criscuolo** [comment]
Upon cloning, running `npm install`, then `npm run buildAndTest`, headless chrome hangs for a minute then kills itself without running the test:

https://gist.github.com/james-criscuolo/ef582791075749eac377b106c27e47bb

Once you've built, `npm run commandLineTest` does that same thing.

**Comment by jlaine** [comment]
@james-criscuolo can you try clearing out your node_modules and package-lock.json?

Are you using Chrome or Chromium on your local machine?

**Comment by james-criscuolo** [comment]
I am using Chrome, and it was a fresh clone. I can delete the package-lock after the fact, but it wouldn't have affected it.

**Comment by jlaine** [comment]
That's odd, `npm run buildAndTest` works fine both on my laptop and on Travis. Is Chrome on your PATH? You can define a CHOME_BIN environment variable to point karma to a specific Chrome installation.

**Comment by james-criscuolo** [comment]
What does the logging look like for you? Specifically, what comes after the "starting Chrome Headless" line. Maybe there is a way to up debugging on that.

**Comment by james-criscuolo** [comment]
I haven't been actively exploring this, I'm curious why Chrome Headless has any output for me, I should have some time this afternoon to investigate.

**Comment by jlaine** [comment]
@james-criscuolo if you have a chance to try again after setting CHROME_BIN it'd be great. I currently have a branch which uses arrow functions for SDH but it depends on switching to Chrome for the unit tests.

**Comment by james-criscuolo** [comment]
I've tried setting CHROME_BIN and still nothing. I looked a bit yesterday and did find a few depressing issues:

https://github.com/karma-runner/karma/issues/2652#issuecomment-335599121
https://github.com/karma-runner/karma-chrome-launcher/issues/154

I've tried several things from those tickets as well, nothing works. I'm going to try to get more logging out of this, but I can't say my setup is too out of the ordinary, so it'd be hard to say what is causing this.

**Comment by james-criscuolo** [comment]
So turning up logging showed me that setting my CHROME_BIN had done nothing. Once I got that squared away, everything worked. For reference, they hardcode where Mac installs Chrome in your applications folder. I change "Google Chrome" to "Chrome", so it no longer works. I feel like there should be a better way for them to do that, but that's another story.

**Pull request merged**
