### PR TITLE
Add 2 unit tests for 423 response on REGISTER

### PR DESCRIPTION
**Pull request by ryan-rowland**
We're looking at implementing 423s in the future and wanted to make sure it's always handled correctly. I figured I'd commit them back to master as this functionality doesn't seem to be under harness yet.

### CODE REVIEW

**Comment by wakamoleguy** [comment]
Thank you for the contribution!  It's always nice to see some new unit tests.  I have a couple sticking points, though.

My first nitpick would be that the mocked response objects seem a little gratuitous in their responses.  Are we really testing that we read the 'min-expires' header when requesting *any* header returns 123?  I'd much prefer to see a response object that is closer to the real thing and depends less on the specific implementation of `RegisterContext.receiveResponse`.

Secondly, I notice [the RFC says](https://tools.ietf.org/html/rfc3261#section-10.2.8) that the retry should contain an expires equal to *or greater than* the one specified in the 423 response.  I'd like the unit test to match that more closely.

**Comment by ryan-rowland** [comment]
@wakamoleguy Fair enough. I've updated both tests to construct an IncomingResponse object and set the appropriate properties, and changed the test assertion to check for an `expires` equal to or greater than the `min-expires` header.

**Comment by wakamoleguy** [comment]
Looks good, thanks!

**Comment by wakamoleguy** [comment]
Whoops...sorry about the misclicks and spam updates.  It's probably time for me to go home.

**Pull request merged**
