### PR TITLE
Original master

### PR DESCRIPTION
**Pull request by edmunfollen**

### CODE REVIEW

**Comment by edmunfollen** [comment]
Merged original repo https://github.com/onsip/SIP.js

**Comment by james-onsip** [comment]
Hi @edmunfollen ,
  Thank you for contributing to SIP.js! It looks like you have some interesting changes, could you please give a little description of what this Pull Request is attempting to do? From a brief look at the overall diff, It looks like there is a Freeswitch specific hack (the piece starting with `if(/[F|f]rom:(\s)*<sip:[0-9]*@pstn(.)*>/.test(request.data)){`), if that is true, I would recommend moving it to the hacks file. 

Also, I'm not sure if the 11 commits are necessary, so if the commits could be cleaned up and explained, that would be great. Lastly, it looks like the travis tests are failing, but it seems it's just a small change for 'jshint', so that would also need to be changed before a merge.

I'm sure we could do the rearranging and `jshint` fixing on our end, but at minimum an explanation would still be necessary (with potential details of how this code has been tested, if at all).

Thanks,
James

**Comment by edmunfollen** [comment]
Hi James,

Sorry for the massive pull request. To be honest, it was a mistake. I
thought I was merging into our own Master branch. My apologies.

This week has been quite hectic due to several issues we had with
FreeSwitch and frozen media. So I didn't find the time to look into this
properly.

Maybe, if you want, you can ignore all those 11 commits and during the
weekend I can create a formal pull request with a better explanation and
less commits. What's your thinking?

Regards,
Arturo.

On 25 January 2016 at 16:05, James Criscuolo <notifications@github.com>
wrote:

> Hi @edmunfollen <https://github.com/edmunfollen> ,
> Thank you for contributing to SIP.js! It looks like you have some
> interesting changes, could you please give a little description of what
> this Pull Request is attempting to do? From a brief look at the overall
> diff, It looks like there is a Freeswitch specific hack (the piece starting
> with if(/[F|f]rom:(\s)*<sip:[0-9]*@pstn(.)*>/.test(request.data)){), if
> that is true, I would recommend moving it to the hacks file.
>
> Also, I'm not sure if the 11 commits are necessary, so if the commits
> could be cleaned up and explained, that would be great. Lastly, it looks
> like the travis tests are failing, but it seems it's just a small change
> for 'jshint', so that would also need to be changed before a merge.
>
> I'm sure we could do the rearranging and jshint fixing on our end, but at
> minimum an explanation would still be necessary (with potential details of
> how this code has been tested, if at all).
>
> Thanks,
> James
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onsip/SIP.js/pull/278#issuecomment-174535335>.
>



-- 
Arturo

**Comment by james-onsip** [comment]
Hi Arturo,
  I've had quite a few weeks of FreeSwitch chaos as well, no need for apologies. Closing this in favor of a formal PR sounds like a good idea. Please don't feel the need to immediately commit this stuff back because you've let the rabbit out of the hat, if it's still a work in development (or just never meant for SIP.js proper) that's ok. It does look like there is some interesting stuff that I'm sure would no doubt be useful for some community members (myself included), but the choice is yours.

Thanks,
James

**Pull request closed without merging**
