### PR TITLE
checks for Array - SIPjs #773

### PR DESCRIPTION
**Pull request by EduardoSellanes**
for the second dtmf that we want to send, 

after the execution of
`const dtmf: DTMF = this.tones.shift();` 
`(this.tones)` is `true` even if `this.tones` is an empty Array

### CODE REVIEW

**Comment by kylekurz** [comment]
Any feedback on this from the SIP.js team? It's been pending for over a month with neither approval nor rejection.

**Comment by james-criscuolo** [comment]
Sorry, coronavirus has slowed us down this past month, but we hope to get back to the project in the next few days.

We are likely to take this PR, but it's worth noting it's for our old API, which will be removed in 0.16.0. We will be having another 0.15.x release, so it will get into a tagged release.

**Comment by kylekurz** [comment]
@james-criscuolo thanks for following up and the additional info. Understandable that things have been a little slower these days. Do you know roughly when 0.16 is coming, just so we have an idea?

**Comment by james-criscuolo** [comment]
I'm hoping within the next few weeks, but you can move to the new API whenever, 0.15.x includes it and at this point it is deemed stable.

**Comment by kylekurz** [comment]
@james-criscuolo awesome, thanks for the info.

**Comment by john-e-riordan** [comment]
As this looks good and while it has no impact on the new API, I'm going to pull this into my pre 0.16 branch so I can also update the 0.16.0 branch with it. So this will go out soonish in next 0.15.x.

**Comment by kylekurz** [comment]
@john-e-riordan thank you!

**Comment by james-criscuolo** [comment]
Closing this in favor of #787, which now has this commit. Thanks again!

**Pull request closed without merging**
